// @ts-ignore - generated by OpenNext during build
import { default as nextHandler } from './.open-next/worker.js';

export default {
  fetch: nextHandler.fetch,
};

/**
 * Persistent, single-writer application state for the quiz runtime.
 * Durable Object storage prevents the data-loss and cross-isolate race
 * conditions that occur when writing JSON files from Cloudflare Workers.
 */
export class QuizStore {
  constructor(state, env) {
    this.state = state;
    this.env = env;
  }

  async fetch(request) {
    const url = new URL(request.url);

    if (request.method === 'GET' && url.pathname === '/state') {
      const current = await this.state.storage.get('state');
      if (!current) {
        return new Response(null, { status: 404 });
      }
      return Response.json(current);
    }

    if (request.method === 'PUT' && url.pathname === '/state') {
      const body = await request.json();
      const expectedRevision = Number(body?.expectedRevision ?? 0);
      const data = body?.data;
      if (!data || typeof data !== 'object') {
        return Response.json({ error: 'Invalid state payload' }, { status: 400 });
      }

      let response;
      await this.state.storage.transaction(async (txn) => {
        const current = await txn.get('state');
        const currentRevision = Number(current?.revision ?? 0);
        if (currentRevision !== expectedRevision) {
          response = Response.json(
            { error: 'Revision conflict', revision: currentRevision },
            { status: 409 }
          );
          return;
        }

        const next = {
          revision: currentRevision + 1,
          updatedAt: new Date().toISOString(),
          data,
        };
        await txn.put('state', next);
        response = Response.json({ revision: next.revision });
      });

      return response ?? Response.json({ error: 'Storage transaction failed' }, { status: 500 });
    }

    if (request.method === 'GET' && url.pathname === '/health') {
      return Response.json({ ok: true, storage: 'durable-object' });
    }

    return new Response('Not found', { status: 404 });
  }
}
